apiVersion: 1

datasources:
  - name: 'prometheus-monitoring-1'
    type: 'prometheus'
    access: 'proxy'
    orgId: 1
    url: 'http://aiassistant-prometheus:9090'
    isDefault: true
    version: 1
    editable: true
